In [4]:
import tensorflow_hub as hub
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import cv2

In [8]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import cv2

model_path = "pneumonia_model/"  
layer = hub.KerasLayer(model_path, trainable=False)

image_path = "test_no_pneumonia.jpg"  
image = cv2.imread(image_path)
image = cv2.resize(image, (224, 224))  

input_image = tf.expand_dims(tf.cast(image, tf.float32), axis=0)

predictions = layer(input_image, training=False)

print(predictions)


tf.Tensor([[1.0000000e+00 3.6066771e-16]], shape=(1, 2), dtype=float32)


In [9]:
print(predictions)


tf.Tensor([[1.0000000e+00 3.6066771e-16]], shape=(1, 2), dtype=float32)


In [6]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [12]:
model_path = "skin_model/"  
layer = hub.KerasLayer(model_path, trainable=False)

image_path = "test_bcc.jpg"  
image = cv2.imread(image_path)
image = cv2.resize(image, (28, 28))  
input_image = tf.expand_dims(tf.cast(image, tf.float32), axis=0)

predictions = layer(input_image, training=False)

print(predictions)

tf.Tensor([[0. 0. 0. 0. 0. 0. 1.]], shape=(1, 7), dtype=float32)
